# Generated by Django 4.2.23 on 2025-08-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='DarkReport.project')),
            ],
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconnaissance', models.CharField(max_length=500)),
                ('weaponization', models.CharField(max_length=500)),
                ('delivery', models.CharField(max_length=500)),
                ('exploitation', models.CharField(max_length=500)),
                ('installation', models.CharField(max_length=500)),
                ('commandcontrol', models.CharField(max_length=500)),
                ('actions', models.CharField(max_length=500)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finds', to='DarkReport.report')),
            ],
        ),
    ]
