# Generated by Django 4.2.23 on 2025-08-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DarkReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
