# Generated by Django 4.2.23 on 2025-08-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DarkReport', '0002_project_description_alter_project_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='target_name',
            new_name='target',
        ),
    ]
