# Generated by Django 4.2.23 on 2025-08-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DarkReport', '0004_find_vulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='cve',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
