# Generated by Django 4.2.23 on 2025-08-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DarkReport', '0005_find_cve'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='recon_scan_file',
            field=models.FileField(blank=True, null=True, upload_to='reconnaissance/'),
        ),
    ]
