# Generated by Django 4.2.23 on 2025-08-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DarkReport', '0006_find_recon_scan_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='find',
            old_name='recon_scan_file',
            new_name='recon_file',
        ),
    ]
