# Generated by Django 4.2.23 on 2025-08-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DarkReport', '0007_rename_recon_scan_file_find_recon_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='recon_file',
            field=models.FileField(blank=True, null=True, upload_to='recon/'),
        ),
    ]
